### ISSUE TITLE
[feature] load a list of reports from fflogs

### ISSUE THREAD

**Issue by Necroskillz** [k0etsu/xivodreview#18]
Awesome tool, i was looking for something like what echo players are using and was pleasantly surprised to finds this.

One feature that would be nice is to show a list of reports (personal or fc/static) loaded from fflogs api and instead of having to fill it manually.

If this also found the vod/stream that best overlaps the timestamp range of the pulls in the reports via the youtube api, that would be sick (if its possible)

**Comment by k0etsu** [comment]
So raidplan's vod review tool does this, albeit only with twitch vods as far as I'm aware.

I'm intrigued on how this would work and would be interested in implementing it but with some caveats. Raidplan currently requires a user to enter their twitch channel initially as a parameter that they store and then when a report link is supplied, it brings up the vod that best fits the timeframe.

I would have to explore both the twitch/youtube api to see how they are achieving this but it doesn't seem too crazy (unless your youtube channel just has a ton of videos which could make parsing a bit lengthy).

The biggest deterrent, currently, is how this would affect UX as that is something I'm not great at and I already have some UI/UX overhauls planned to make the reporting section easier to navigate when you have large reports (like during this last tier). I will revisit once those changes have been pushed through.

**Comment by k0etsu** [comment]
After exploring this for a bit I've decided that it is a bit out of scope for what the original premise of the app is, which is to offer a solution that does not require anyone to log in as a prerequisite in using the tool.
