### ISSUE TITLE
player can't load age restricted videos

### ISSUE THREAD

**Issue by Necroskillz** [k0etsu/xivodreview#20]
Sometimes youtube age restricts my stream, and that makes the site unable to load the video even if im logged in to youtube.

Example: https://xivodreview.com/?youtube=OqmQCA2fVOc&fflogs=gpqtVadLrWNFj93b&offset=0

**Comment by k0etsu** [comment]
Unfortunately, this is a flag that is set on YouTube's side and can't really be messed with by third-party apps. The most you can probably do is try to appeal the age-restriction (https://support.google.com/youtube/answer/1153367?sjid=10413506961989388605-NA) or try to minimize anything that can cause it to happen.
